#!/bin/sh
#
# @name 3DR Iris Quadrotor SITL
#
# @type Quadrotor Wide
#
# @maintainer Julian Oes <julian@oes.ch>
#

. ${R}etc/init.d/rc.mc_defaults


param set-default CA_AIRFRAME 0

param set-default CA_ROTOR_COUNT 4
param set-default CA_ROTOR0_PX 0.1515
param set-default CA_ROTOR0_PY 0.245
param set-default CA_ROTOR0_KM 0.05
param set-default CA_ROTOR1_PX -0.1515
param set-default CA_ROTOR1_PY -0.1875
param set-default CA_ROTOR1_KM 0.05
param set-default CA_ROTOR2_PX 0.1515
param set-default CA_ROTOR2_PY -0.245
param set-default CA_ROTOR2_KM -0.05
param set-default CA_ROTOR3_PX -0.1515
param set-default CA_ROTOR3_PY 0.1875
param set-default CA_ROTOR3_KM -0.05

param set-default PWM_MAIN_FUNC1 101
param set-default PWM_MAIN_FUNC2 102
param set-default PWM_MAIN_FUNC3 103
param set-default PWM_MAIN_FUNC4 104

# Gimbal
param set-default PWM_MAIN_FUNC7 420
param set-default PWM_MAIN_FUNC8 421
param set-default PWM_MAIN_FUNC9 422
# Landing gear
param set-default PWM_MAIN_FUNC10 400
param set-default PWM_MAIN_FUNC11 400

# Camera and Gimbal control
param set-default TRIG_INTERFACE 3
param set-default TRIG_MODE 4
param set-default MNT_MODE_IN 4
param set-default MNT_MODE_OUT 2

# if [ $AUTOCNF = yes ]
# then
#     param set MC_PITCHRATE_P 0.1
#     param set MC_PITCHRATE_I 0.05
#     param set MC_PITCH_P 6.0
#     param set MC_ROLLRATE_P 0.15
#     param set MC_ROLLRATE_I 0.1
#     param set MC_ROLL_P 6.0
#     param set MPC_XY_VEL_I_ACC 4
#     param set MPC_XY_VEL_P_ACC 3

#     param set RTL_DESCEND_ALT 10
#     param set RTL_LAND_DELAY 0

#     param set TRIG_INTERFACE 3
#     param set TRIG_MODE 4
#     param set MNT_MODE_IN 0
#     param set MAV_PROTO_VER 2
# fi
